include:
  - project: 'nitrokey/gitlab-ci'
    file:
      - 'common-jobs/common_jobs.yml'
      - 'common-jobs/github_commands.yml'

stages:
  - pull-github
  - checks
  - build
  - deploy
  - commands

variables:
  GIT_STRATEGY: clone            
  GIT_DEPTH: 0                    
  GIT_SUBMODULE_STRATEGY: recursive 
  SCRIPTS_REPO: git@git.nitrokey.com:nitrokey/gitlab-ci.git
  REPO_GROUP: nitrokey
  REPO_NAME: nextbox
  MAIN_BRANCH: master
  COMMAND_MERGE_ENABLED: "true"


checks:
  image: registry.git.nitrokey.com/nitrokey/nextbox/build-image:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $COMMAND_BOT == "nitrokey-ci" && $COMMAND == "build"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - docker-arm
  stage: checks
  script:
    - apt update
    - apt install -qy python3 python3-pip python3-apt python3-distutils
    - pip install -r requirements.txt
    - pip install -r daemon/requirements.txt
    - python3 -m mypy daemon/

build-image:
  image: registry.git.nitrokey.com/nitrokey/nextbox/build-image:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $MAIN_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $COMMAND_BOT == "nitrokey-ci" && $COMMAND == "build"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - docker-arm
  stage: build
  script:
    - pwd
    - cd image
    - make
  after_script:
    - !reference [notify_github, script] # use notify_github from include
    - mkdir -p artifacts
    - cp ./image/gen-image/deploy/*final.zip ./artifacts/
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts

